name: Makefile CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Debugging Log
      run: |
        make clean --debug=v SHELL='sh -xvp'
    - name: Target Log
      run: |
        make -p
    - name: Run check
      run: |
        make clean
        make check
