name: Makefile CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Run help
      run: |
        make clean
        make help
    - name: Run check
      run: |
        make clean
        make check
    - name: Run test
      run: |
        make clean
        make test
    - name: Run test across configurations
      run: |
        make clean
        make test BOWERBIRD_TEST/CONFIG/FAIL_EXIT_CODE=1
        make test BOWERBIRD_TEST/CONFIG/FAIL_EXIT_CODE=0
    - name: Run default
      run: |
        make clean
        make
